# Generated by Django 3.1.1 on 2020-09-25 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0006_auto_20200925_1435'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='Click link to view blog post', max_length=255),
        ),
    ]
