# Generated by Django 3.1.1 on 2020-09-29 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0010_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
