# Generated by Django 3.1.1 on 2020-09-29 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hblog', '0012_auto_20200929_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='youtube_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
